terraform-ibm-modules/terraform-ibm-toolkit-vpc-subnets

module.yaml
test/stages/stage1-vpc.tf

Adds metadata entry for vpc_name variable

---

.github/workflows/publish-assets.yaml
module.yaml

Removes unneccesary vpc_id variable reference

---

.github/workflows/verify.yaml
main.tf
outputs.tf
provider.tf
test/stages/stage1-resource-group.tf
test/stages/stage2-subnets.tf
test/stages/variables.tf
variables.tf

Adds support for passing ipv4 cidr values in for vpc

---

README.md

Update values from starting template with content for the subnet module.

Update dependencies and example

---

main.tf
outputs.tf
variables.tf

Adds provision variable and logic to look up existing subnet

---

variables.tf

Fixes quotes used in ipv4_cidr_blocks variable description

---

main.tf

Adds logic to print subnet names to force sequencing

---

main.tf
outputs.tf

Only returns subnets from data block of not provisioning

---

module.yaml

Adds dependency on cos_bucket for flow_log_cos_bucket_name

---

outputs.tf

Adds name to output

---

main.tf
variables.tf

Adds default ACL rules that allow for extension

---

main.tf
test/stages/stage2-subnets.tf

Adds acl_rules to test case

---

main.tf
module.yaml
test/stages/stage1-gateways.tf
test/stages/stage1-vpc.tf
test/stages/stage2-subnets.tf
test/stages/variables.tf
variables.tf

Removes vpc_id and flattens ipv4_cidr_blocks input

---

module.yaml

Updates metadata so that gateways aren't autowired

---

main.tf

Provisions ACL in correct resource group

---

main.tf

Adds checks for null when using variables in templates

---

main.tf
test/stages/stage0.tf
test/stages/stage1-gateways.tf
test/stages/stage1-vpc.tf

Signed-off-by: Andrew Trice <amtrice@us.ibm.com>

added mirror ingress/egress rules

---

main.tf

Signed-off-by: Andrew Trice <amtrice@us.ibm.com>

added name prefix so acl rule names are unique

---

main.tf

Signed-off-by: Andrew Trice <amtrice@us.ibm.com>

revert unique names... it didn't fix the overlap

---

main.tf

Signed-off-by: Andrew Trice <amtrice@us.ibm.com>

changing subnet rule naming to avoid duplicates

---

.github/workflows/publish-assets.yaml
.github/workflows/verify.yaml
module.yaml

Adds workflow to delete test gitops repo manually

---

module.yaml

Fixes gateways dependency metadata reference

---

.github/workflows/verify.yaml
variables.tf
version.tf

Adds type definition for acl_rules and sets min version to v0.15

---

.github/scripts/validate-deploy.sh
.github/workflows/verify.yaml
main.tf
outputs.tf
test/stages/stage1-gateways.tf
test/stages/stage1-resource-group.tf
test/stages/stage1-vpc.tf
test/stages/stage2-subnets.tf
test/stages/variables.tf
variables.tf

Adds enabled input variable

---

.github/scripts/validate-deploy.sh
.github/workflows/verify.yaml
main.tf
outputs.tf
test/stages/stage1-gateways.tf
test/stages/stage1-resource-group.tf
test/stages/stage1-vpc.tf
test/stages/stage2-subnets.tf
test/stages/variables.tf
variables.tf

Removes unnecessary enabled flag

---

README.md
module.yaml

Adds registry id to metadata

---

main.tf

- Creates the network acl rules in a separate ibm_is_network_acl_rule block to prevent triggering a change on subsequent plan
cloud-native-toolkit/terraform-ibm-vpc-vsi#37

Separates rule definition from network acl creation

---

README.md
module.yaml

Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
**Check the relevant boxes:**
- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

move from CN: Signed-off-by: Bala <@balasgit>
